-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH, B.GENDER, COUNT(DISTINCT A.USER_ID) USERS FROM ONLINE_SALE A LEFT JOIN USER_INFO B ON A.USER_ID=B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, B.GENDER
ORDER BY YEAR, MONTH, B.GENDER